---
AbcMetricMethodCheck:            { score: 11.8 }
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 390 }
ClassNameCheck:                  { pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/ }
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 2 }
CyclomaticComplexityMethodCheck: { complexity: 5 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
# TODO: decrease line_count to 5 to 10
MethodLineCountCheck:            { line_count: 20 }
MethodNameCheck:                 { pattern: !ruby/regexp /\A(?:[a-z\d](?:_?[a-z\d])+[?!=]?|\[\]=?|==|<=>|[+*&|-])\z/ }
ModuleLineCountCheck:            { line_count: 392 }
ModuleNameCheck:                 { pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/ }
# TODO: decrease parameter_count to 2 or less
ParameterNumberCheck:            { parameter_count: 3 }
